####################################################
#This program generates 
#*** esterel: exit: errors during "sccausal" (139)
####################################################

all:
	esterelv6_03-3 -causal -B UDP_FLOW UDP_FLOW.strl SOURCE.strl P_MOD.strl P_MOD1to2.strl SINK.strl INITIALIZE_SINK.strl COMP_DATA.strl FIT_RANGE_MOD.strl FIT_RANGE_SNK.strl FIT_RANGE_SRC.strl SWITCH.strl WAIT_SIG1.strl WAIT_SIG2.strl TIMER.strl
